spring:
  application:
    name: Freewheelin
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/h2db;AUTO_SERVER=true
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
jwt:
  secret-key: a1b2c3d4e5f6g7h8i9j10k11l12m13n14
  access-token-expire-minutes: 10